In [1]:
import numpy as np 
import pandas as pd

In [13]:
s =['I am going to market',
   'I am going to my house and then going to my friend house',
   'Market is near my house',
   'My friend is going to his house and the going to market']
for i in s:
    op = i.split()
    u,c = np.unique(op,return_counts=True)
    #print(u)
    print(c)

[1 1 1 1 1]
[1 1 1 1 2 2 2 1 2]
[1 1 1 1 1]
[1 1 1 2 1 1 1 1 1 2]


In [6]:
z = 'I am going to my house and then going to my friend house'
op = z.split()
u,c = np.unique(op,return_counts=True)
print(c)

[1 1 1 1 2 2 2 1 2]


In [17]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
op = v.fit_transform(s)
op = op.toarray()
op

array([[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 1, 1, 2, 0, 2, 0, 0, 2, 0, 0, 1, 2],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2]], dtype=int64)

In [19]:
v.get_feature_names_out()

array(['am', 'and', 'friend', 'going', 'his', 'house', 'is', 'market',
       'my', 'near', 'the', 'then', 'to'], dtype=object)

In [20]:
df = pd.DataFrame(op,columns= v.get_feature_names_out())
df

am  and  friend  going  his  house  is  market  my  near  the  then  to
0   1    0       0      1    0      0   0       1   0     0    0     0   1
1   1    1       1      2    0      2   0       0   2     0    0     1   2
2   0    0       0      0    0      1   1       1   1     1    0     0   0
3   0    1       1      2    1      1   1       1   1     0    1     0   2