#### Numpy
- Numpy stands for Numerical Python
- Basic and one of the most important library for numerical computations
- Supports N-dimensional array objects that can be used for processing multidimensional data
- Supports different data-types

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


##### Using Numpy we can perform

- Mathematical and logical operations on arrays
- Fourier transforms
- Linear algebra operations
- Random number generation

In [3]:
import numpy as np

### How to Create arrray
##### 1. using np.array method

- Ordered collection of elements of basic data types of given length
- Syntax: numpy.array(object)

In [4]:
array1 = np.array([4,5,6])
print(array1)
print(type(array1))
print(array1.dtype)

[4 5 6]
<class 'numpy.ndarray'>
int32


In [10]:
array2=np.array([3,4,6]) # 0 = 3, 1 = 4, 2 = 6  
print(array2[2])
print(type(array2[1]))

6
<class 'numpy.int32'>


In [8]:
type(array2)

numpy.ndarray

In [9]:
print(array2.dtype)

int32


##### Important Note - 
- Arrray in python is collection of different datatype elements
- All elements are coerced(converted) to same data type i.e conversion will be done of lower datatype elements to higher datatype elements

In [11]:
arr1=np.array([2,3,5.6,"avinash"])
print(arr1)
print(type(arr1))
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

['2' '3' '5.6' 'avinash']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### 2. Generate arrays using arange( )
- numpy.arange()- returns equally spaced numbers with in the given range based on step size
- Syntax:numpy.arange(start,stop,step)
- start - start of interval range
- stop - end of interval range
- step - step size of interval

In [8]:
a1=np.arange(10)
print(a1)

# for (int i = 0; i < 10; i++)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a3=np.arange(start=110,stop=120,step=3) # i = i + 3
print(a3)

# for(int i = 110; i < 120; i = i + 3) 

[110 113 116 119]


- Create array of elements between 70 to 50 with 5 difference

In [12]:
a4 = np.arange(start=70,stop=50,step=-5) #
print(a4)
# for(int i = 70; i > 50; i = i - 5)

[70 65 60 55]


#### 3. Generate arrays using ones
- numpy.ones()- returns an array of given shape and type filled with ones
- Syntax:numpy.ones(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [13]:
arr4 = np.ones(6)
print(arr4)
print(type(arr4[5]))

[1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [14]:
arr5= np.ones((3,7),int) # 3 rows & 7 columns
print(arr5)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


##### 4. Generate arrays using zeros
- numpy.zeros()- returns an array of given shape and type filled with zeros
- Syntax:numpy.zeros(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [15]:
arr7= np.zeros(6)
print(arr7)

[0. 0. 0. 0. 0. 0.]


In [16]:
arr8= np.zeros((3,7),int)
print(arr8)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


#### 5. Generate arrays using random.rand( )
- numpy.random.rand()- returns an array of given shape filled with random values
- Syntax:numpy.random.rand(shape)
- shape - integer or sequence of integers

In [17]:
# Create 1D array of 5 random elements between 0 to 1
a10 = np.random.rand(10)
print(a10)

[0.53057154 0.03048933 0.64440232 0.55770695 0.42765156 0.50958622
 0.25098057 0.27542136 0.31636228 0.23815328]


In [19]:
# Create 2D array of 35 random elements between 0 to 1
a11=np.random.rand(7,5) # 7 rows & 5 columns
print(a11)

[[0.42628645 0.59973648 0.95217141 0.22654314 0.84565689]
 [0.36294334 0.09763472 0.93023099 0.36460878 0.07312726]
 [0.71063331 0.94203515 0.14085837 0.74210685 0.09856286]
 [0.46201585 0.89844139 0.32607985 0.86834785 0.24691216]
 [0.21386199 0.11407277 0.23239247 0.98872955 0.78178304]
 [0.68297201 0.15244793 0.82249319 0.84877341 0.27863278]
 [0.57185083 0.23818038 0.54361659 0.50679552 0.74993019]]


In [21]:
# Create 2D array of 35 random int elements between 100 to 150
a12 = np.random.randint(100,150,(7,5))
print(a12)

[[131 133 114 139 135]
 [129 133 137 122 128]
 [122 127 141 114 100]
 [100 121 105 100 139]
 [101 128 124 105 124]
 [125 102 145 140 104]
 [136 149 137 103 134]]


1. Speed - Array is faster than list
2. Memory Storage - Array takes less memory than list

Reshape - We can change shape of arrays

In [22]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


In [23]:
b = a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [24]:
b.shape

(4, 2)

##### Arrithmetic Operations in Numpy

In [25]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [26]:
print("addditon of a1 and a2 is\n", np.add(a1,a2))

addditon of a1 and a2 is
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [27]:
print("subtract of a1 and a2 is\n",np.subtract(a1,a2))

subtract of a1 and a2 is
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [28]:
print("mul of a1 and a2 is\n",np.multiply(a1,a2))

mul of a1 and a2 is
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [29]:
print("divide of a1 and a2 is\n",np.divide(a2,a1))

divide of a1 and a2 is
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [30]:
print("remainder of a1 and a2 is\n",np.remainder(a2,a1))

remainder of a1 and a2 is
 [[0 0 1]
 [2 0 4]
 [3 2 1]]


In [26]:
pip install numpy