#### Numpy
- Numpy stands for Numerical Python
- Basic and one of the most important library for numerical computations
- Supports N-dimensional array objects that can be used for processing multidimensional data
- Supports different data-types

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


##### Using Numpy we can perform

- Mathematical and logical operations on arrays
- Fourier transforms
- Linear algebra operations
- Random number generation

In [3]:
import numpy as np

### How to Create arrray
##### 1. using np.array method

- Ordered collection of elements of basic data types of given length
- Syntax: numpy.array(object)

In [5]:
array1 = np.array([4,5,6])
print(array1)
print(type(array1))
print(array1.dtype)

[4 5 6]
<class 'numpy.ndarray'>
int32


In [6]:
array2=np.array([3,4,6]) # 0 = 3, 1 = 4, 2 = 6  
print(array2[2])
print(type(array2[2]))

6
<class 'numpy.int32'>


In [7]:
type(array2)

numpy.ndarray

In [8]:
print(array2.dtype)

int32


##### Important Note - 
- Arrray in python is collection of different datatype elements
- All elements are coerced(converted) to same data type i.e conversion will be done of lower datatype elements to higher datatype elements

In [10]:
arr1=np.array([2,3,5.6,"avinash"])
print(arr1)
print(type(arr1))
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

['2' '3' '5.6' 'avinash']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### 2. Generate arrays using arange( )
- numpy.arange()- returns equally spaced numbers with in the given range based on step size
- Syntax:numpy.arange(start,stop,step)
- start - start of interval range
- stop - end of interval range
- step - step size of interval

In [11]:
a1=np.arange(10)
print(a1)

# for (int i = 0; i < 10; i++)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
a3=np.arange(start=110,stop=120,step=3) # i = i + 3
print(a3)

# for(int i = 110; i < 120; i = i + 3) 

[110 113 116 119]


- Create array of elements between 70 to 50 with 5 difference

In [13]:
a4 = np.arange(start=70,stop=50,step=-5) #
print(a4)
# for(int i = 70; i > 50; i = i - 5)

[70 65 60 55]


#### 3. Generate arrays using ones
- numpy.ones()- returns an array of given shape and type filled with ones
- Syntax:numpy.ones(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [14]:
arr4 = np.ones(6)
print(arr4)
print(type(arr4[5]))

[1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [15]:
arr5= np.ones((3,7),int) # 3 rows & 7 columns
print(arr5)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


##### 4. Generate arrays using zeros
- numpy.zeros()- returns an array of given shape and type filled with zeros
- Syntax:numpy.zeros(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [16]:
arr7= np.zeros(6)
print(arr7)

[0. 0. 0. 0. 0. 0.]


In [17]:
arr8= np.zeros((3,7),int)
print(arr8)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


#### 5. Generate arrays using random.rand( )
- numpy.random.rand()- returns an array of given shape filled with random values
- Syntax:numpy.random.rand(shape)
- shape - integer or sequence of integers

In [18]:
# Create 1D array of 10 random elements between 0 to 1
a10 = np.random.rand(10)
print(a10)

[0.14077556 0.75428277 0.04612999 0.1293134  0.89371423 0.3914597
 0.10835818 0.58392257 0.21094422 0.2656851 ]


In [19]:
# Create 2D array of 35 random elements between 0 to 1
a11=np.random.rand(7,5) # 7 rows & 5 columns
print(a11)

[[0.01994745 0.44702677 0.63551951 0.88383305 0.07636236]
 [0.09895497 0.14283006 0.54176419 0.05563754 0.861544  ]
 [0.85487844 0.26198729 0.42165158 0.09564142 0.50624775]
 [0.15834968 0.14684744 0.19161611 0.55861273 0.53828986]
 [0.59577131 0.97263688 0.71176245 0.54171132 0.29187107]
 [0.61638688 0.9060879  0.81891676 0.99193207 0.61454481]
 [0.60885843 0.93948057 0.14356906 0.4706732  0.35232476]]


In [20]:
# Create 2D array of 35 random int elements between 100 to 150
a12 = np.random.randint(100,150,(7,5))
print(a12)

[[138 119 109 119 117]
 [120 131 144 124 145]
 [131 118 121 106 129]
 [133 140 115 132 119]
 [139 131 144 133 101]
 [122 121 141 125 113]
 [139 106 140 129 113]]


1. Speed - Array is faster than list
2. Memory Storage - Array takes less memory than list

Reshape - We can change shape of arrays

In [24]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


In [26]:
b = a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [27]:
b.shape

(4, 2)

##### Arrithmetic Operations in Numpy

In [28]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [29]:
print("addditon of a1 and a2 is\n", np.add(a1,a2))

addditon of a1 and a2 is
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [30]:
print("subtract of a1 and a2 is\n",np.subtract(a1,a2))

subtract of a1 and a2 is
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [31]:
print("mul of a1 and a2 is\n",np.multiply(a1,a2))

mul of a1 and a2 is
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [32]:
print("divide of a1 and a2 is\n",np.divide(a2,a1))

divide of a1 and a2 is
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [33]:
print("remainder of a1 and a2 is\n",np.remainder(a2,a1))

remainder of a1 and a2 is
 [[0 0 1]
 [2 0 4]
 [3 2 1]]
